apiVersion: v1
kind: Service
metadata:
  name: telemetry-engine
  labels:
    app.kubernetes.io/name: telemetry-engine
spec:
  selector:
    app: telemetry-engine
  ports:
    - name: telemetry-udp
      port: 50051
      targetPort: 50051
      protocol: UDP
    - name: health-http
      port: 8080
      targetPort: 8080
      protocol: TCP
